CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL DEFAULT 'Admin',
  email VARCHAR(191) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role VARCHAR(64) NOT NULL DEFAULT 'editor',
  status VARCHAR(64) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cms_content (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tab VARCHAR(64) NOT NULL,
  section VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  value LONGTEXT,
  type VARCHAR(64) NOT NULL DEFAULT 'text',
  enabled TINYINT NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY cms_tab_section_key (tab(40), section(40), `key`(40))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS packages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(191) NOT NULL UNIQUE,
  category VARCHAR(191) NOT NULL DEFAULT 'Adventure',
  duration VARCHAR(191),
  price_from DOUBLE,
  currency VARCHAR(16) NOT NULL DEFAULT 'USD',
  description TEXT,
  highlights TEXT,
  inclusions TEXT,
  itinerary LONGTEXT,
  image_url TEXT,
  rating DOUBLE DEFAULT 0,
  difficulty VARCHAR(64) DEFAULT 'Moderate',
  featured TINYINT NOT NULL DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1,
  tagline TEXT,
  badge VARCHAR(191),
  group_size VARCHAR(191),
  season VARCHAR(191),
  exclusions TEXT,
  gallery_json LONGTEXT,
  related_slugs_json TEXT,
  about_label VARCHAR(191),
  itinerary_heading VARCHAR(191),
  gallery_heading VARCHAR(191),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS package_categories (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  slug VARCHAR(191) NOT NULL UNIQUE,
  package_count INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bookings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  booking_id VARCHAR(191) NOT NULL UNIQUE,
  customer_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255),
  customer_phone VARCHAR(64),
  package_name VARCHAR(255) NOT NULL,
  travel_date VARCHAR(64),
  guests INT DEFAULT 1,
  status VARCHAR(64) NOT NULL DEFAULT 'pending',
  payment_status VARCHAR(64) NOT NULL DEFAULT 'unpaid',
  amount DOUBLE,
  currency VARCHAR(16) NOT NULL DEFAULT 'USD',
  notes TEXT,
  source VARCHAR(64) DEFAULT 'website',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contact_submissions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  company VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(64),
  message TEXT NOT NULL,
  source VARCHAR(64) DEFAULT 'website',
  status VARCHAR(64) NOT NULL DEFAULT 'unread',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gallery_items (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  alt_text VARCHAR(255),
  image_url TEXT NOT NULL,
  album VARCHAR(191) DEFAULT 'General',
  sort_order INT DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1,
  media_type VARCHAR(32) DEFAULT 'image',
  video_url TEXT,
  poster_url TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_posts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(191) NOT NULL UNIQUE,
  excerpt TEXT,
  content LONGTEXT,
  author VARCHAR(191) DEFAULT 'Caledor Team',
  category VARCHAR(191) DEFAULT 'Uncategorized',
  tags TEXT,
  image_url TEXT,
  featured TINYINT NOT NULL DEFAULT 0,
  published TINYINT NOT NULL DEFAULT 0,
  published_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(191) NOT NULL UNIQUE,
  value TEXT,
  group_name VARCHAR(64) DEFAULT 'general',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(64) NOT NULL DEFAULT 'info',
  title VARCHAR(255) NOT NULL,
  message TEXT,
  `read` TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faqs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category VARCHAR(191) DEFAULT 'General',
  sort_order INT DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
